### ISSUE TITLE
Why do not support go1.19

### ISSUE THREAD

**Issue by lycheezhou** [arl/statsviz#101]
![image](https://user-images.githubusercontent.com/33309728/204694678-055e7a60-cba0-46c7-bea6-d8c1e8eb7949.png)

**Comment by arl** [comment]
Hi @lycheezhou thanks for reporting.
Statsviz `go.mod` indicates a minimum go version of `1.17`. So you can use Statsviz with any go version that is at least `1.17`. For example I'm using go1.19 and I don't have any problems.

So I don't really understand this error message in the context of Statsviz main go.mod file. This seems printed by some code editor. What are you trying to do? And what is not working?
Thanks
