### ISSUE TITLE
Usage with fasthttp?

### ISSUE THREAD

**Issue by zekroTJA** [arl/statsviz#12]
Is it somehow possible to use this package with [fasthttp](https://github.com/valyala/fasthttp) as HTTP wrapper in combination with [fasthttp-routing](github.com/qiangxue/fasthttp-routing)?

Because I really like the project and really want to integrate it into one of my projects which bases on these packages.

**Comment by arl** [comment]
I've never used fasthttp. If it's somewhat compatible with standard http.Handler then it might be possible, but I'm not sure.

Note that under the hood statsviz needs 2 handlers, the first for the web ui and the second for web socket.

You could also use net/http for statsviz and keep the rest of your application with fasthttp, apart from a slightly bigger binary size it shouldn't be a problem.
Let me know what you find

**Comment by nupamore** [comment]
Http requests are simply resolved using `fasthttpadaptor`. But, there is a problem with the web socket. I'll make a PR for this problem.

**Comment by arl** [comment]
Hey @nupamore 
Thank you to take care of that :+1: 
I'm assigning the issue to you

**Comment by arl** [comment]
Merged in #51 via #35
