### ISSUE TITLE
Usage with echo framework

### ISSUE THREAD

**Issue by diendang271** [arl/statsviz#18]
How to register statviz into echo instance?

**Comment by arl** [comment]
I've never used the echo framework. 
By looking at the documentation I see that there's [WrapHandler](https://pkg.go.dev/github.com/labstack/echo/v4#WrapHandler) which is an adaptor from a standard `http.Handler` (which statsviz handlers are) to an `echo.HandlerFunc` so I guess it's relatively straightforward.

If you come up with something I'd be happy to accept a PR adding a new echo in `./_example/echo` showing how to perform the registering, or you can write it here.

**Comment by diendang271** [comment]
https://github.com/arl/statsviz/pull/22

**Comment by arl** [comment]
Closing since #22 is into master now
