### ISSUE TITLE
Example with Chi Router

### ISSUE THREAD

**Issue by dnnnvx** [arl/statsviz#27]
[Chi](https://github.com/go-chi/chi) is is a lightweight router for HTTP services, 100% compatible with `net/http`. Should be awesome to get an example with it, something like (following the `gorilla/mux` example):
``` go
r := chi.NewRouter()
r.Get("/debug/statsviz/ws", statsviz.Ws)
r.Handle("/debug/statsviz/", statsviz.Index)
```

**Comment by arl** [comment]
added in #29
