### ISSUE TITLE
Example with Gin

### ISSUE THREAD

**Issue by dingdayu** [arl/statsviz#28]
If you are using [Gin](https://github.com/gin-gonic/gin), I hope the following content can help you:

```
router = gin.New()
router.GET("/debug/statsviz/*filepath", func(context *gin.Context) {
	if context.Param("filepath") == "/ws" {
		statsviz.Ws(context.Writer, context.Request)
		return
	}
	statsviz.IndexAtRoot("/debug/statsviz").ServeHTTP(context.Writer, context.Request)
})
router.Run(":8080")
```

### Fail one: "Not Found."

```golang
router = gin.New()
router.GET("/debug/statsviz/ws", gin.WrapF(statsviz.Ws))
router.GET("/debug/statsviz/",  gin.WrapH(statsviz.Index))
router.Run(":8080")
```

Because /debug/statsviz/ is a static directory, Need to register with `router.StaticFS("/more_static", http.Dir("my_file_system"))`

[gin#serving-static-files](https://github.com/gin-gonic/gin#serving-static-files)

### Fail two:  "wildcard route conflicts with existing children"

```golang
router = gin.New()
router.GET("/debug/statsviz/ws", gin.WrapF(statsviz.Ws))
router.GET("/debug/statsviz/*filepath",  gin.WrapH(statsviz.Index))
router.Run(":8080")
```

> panic: '/ws' in new path '/debug/statsviz/ws' conflicts with existing wildcard '/*filepath' in existing prefix '/debug/statsviz/*filepath'

Related issue:

https://github.com/gin-gonic/gin/issues/2016
https://github.com/gin-gonic/gin/issues/1681

> Good debugging tool, hope to help more people.

**Comment by arl** [comment]
Thank you @dnnnvx
I added the example with your code :+1:
