### ISSUE TITLE
[go] add Custom metrics

### ISSUE THREAD

**Issue by Issif** [arl/statsviz#42]
Thanks for this tool, it's really useful for debug.

Could it be possible to add custom metrics and not only those expose by runtime?

I'm developping an application and it exposes a lot of internal metrics.

Thank.

**Comment by arl** [comment]
Thank you. Adding custom metrics is also an idea I've had for statsviz but at the moment it's not possible. The thing is statsviz is made from 2 parts, Go publishes metrics and a web page presents them, both have been developed to show the Go runtime metrics only, and thus many things are hardcoded. Allowing to present arbitrary metrics would be nice but require quite a lot of new stuff, refactoring and new code, we're not there yet.

**Comment by Issif** [comment]
Ok I see. I'll take a deeper look if I find time for and submit a PR. Thanks.

**Comment by arl** [comment]
Ok great. Since that would be an important change, please feel free to share your design/prototype and/or any questions with me here. Happy to help

**Comment by arl** [comment]
Maybe the publishing part could be easily done via expvars.
