### ISSUE TITLE
is there an example for `iris` ?

### ISSUE THREAD

**Issue by sado0823** [arl/statsviz#46]

**Comment by arl** [comment]
Hey @sado0823 no at the moment there isn't any example showing how to configure `statsviz` with https://github.com/kataras/iris.
Since there are many frameworks around, it's not east to keep track and provide example for of all of them. However the majority of code in the examples section comes from pull-requests.
I'd be happy to look into any PR adding an example for this framework

**Comment by sado0823** [comment]
@arl well, i try , but failed.

i try like this
```golang
app.Get("/debug/statsviz", iris.FromStd(statsviz.Index))
	app.Get("/debug/statsviz/{name:string}", func(c *context.Context) {
		if name := c.Params().Get("name"); name == "ws" {
			statsviz.Ws.ServeHTTP(c.ResponseWriter(), c.Request())
			return
		}
		statsviz.Index.ServeHTTP(c.ResponseWriter(), c.Request())
	})
```

when i try this path `http://localhost:27001/debug/statsviz/app.js`, (actually, i can get any `.js` file)
![image](https://user-images.githubusercontent.com/51654192/113848664-495e3c80-97cb-11eb-87bf-7c7e25a85b12.png)


but to `.../debug/statsviz/index.html`, got `404 page not found` :(

to `.../......../ws`, got `bad request`

**Comment by arl** [comment]
I haven't look into the iris framework so I can't help with that specific framework at the moment. 

Did you have a look at how registering statsviz handlers is done with other frameworks? This might help you .

Not sure when I'll have time to look into this but if you haven't found the solution I'll look myself for it.

**Comment by sado0823** [comment]
i saw the example for `gin`, still cannot figure it out :( , you can look into this when you are free, that would be nice

**Comment by trading-peter** [comment]
After some search I figured this way out.
It runs a dedicated http server to serve statsviz but iris controls it for shutdown signals and so on.

With this the iris server is accessible on localhost:8000 and statsviz on localhost:9000.

```golang
app := iris.New()
//.... iris handers and stuff here
// Need to run iris in a separate goroutine so we can start the dedicated http server for statsviz
go app.Listen(":8000")

mux := http.NewServeMux()
statsviz.Register(mux)
statsServer := &http.Server{Addr: ":9000", Handler: mux}

// NewHost puts the http server for statsviz under the control of iris but iris won't touch it's handlers.
app.NewHost(statsServer).ListenAndServe()
```

**Comment by arl** [comment]
@trading-peter that's nice, thank you to look into that. I'll try and add that as an example
