### ISSUE TITLE
[webpage] auto re-connect after restart server?

### ISSUE THREAD

**Issue by bigchai666** [arl/statsviz#47]
the main process may be killed and then restarted while developing. but therefore the webpage stopped receiving metrics from the process? so can you please make the webpage reconnect the backend automatically after the restart?

**Comment by arl** [comment]
Hi @bigchai666 

I agree it would be nice if the statsviz web page were auto-reconnecting after having previously lost the websocket connection from a stopped client.

**Comment by arl** [comment]
@bigchai666 enhancement present on latest master, however not present on tagged version yet.
