### ISSUE TITLE
On firefox, all graphs are in-line

### ISSUE THREAD

**Issue by Issif** [arl/statsviz#81]
Hi,

I tested with Firefox (103.0.2  Arch Linux (64 bits)) and Chromium (104.0.5112.79 Arch Linux (64 bits)). It works perfectly with Chromium but in Firefox, the graphs are not "responsive" and end up in-line.

Left - Firefox
Right - Chromium

![image](https://user-images.githubusercontent.com/4520100/190191227-f7da6d59-ac17-4720-85e0-d156b947734d.png)

**Comment by arl** [comment]
Hi @Issif  thanks for reporting this! I haven't tried on firefox.

ummmh that's indeed very problematic.

I'll try to fix that when I'll come back from holyday

If anybody with more frontend experience than me (probably everybody) want to step up and look into that, please go ahead.
Also, if anybody else has the same problem with Safari, please comment under this issue, thanks

**Comment by Issif** [comment]
I confirm it works since v0.5.1. thank you both

**Comment by arl** [comment]
Cool thank you @Issif ❤️
