### ISSUE TITLE
[Bug] /debug/statsviz/tippy-bundle.umd.min.js.map 404

### ISSUE THREAD

**Issue by jageros** [arl/statsviz#92]
/debug/statsviz/libs/js/tippy-bundle.umd.min.js.map 404 Not Found
/debug/statsviz/libs/js/bootstrap-toggle.min.js.map 404 Not Found
/debug/statsviz/libs/js/popper.min.js.map 404 Not Found
/debug/statsviz/libs/js/bootstrap.bundle.min.js.map 404 Not Found

**Comment by arl** [comment]
Can you share the Go code you're running please?

**Comment by arl** [comment]
@jageros ping

**Comment by arl** [comment]
Those are just browser warnings saying that source maps are not found. Indeed statsviz do not embed source maps of the javascript library it uses. It seems there's 3 ways to proceed forward to _solve_ this (which doesn't in any way impede statsviz functionality):
 - 1. embed source maps (have to check the overall binary increase first)
 - 2. look for `//# sourceMappingURL` javascript comments and remove them
 - 3. use CDN-served source maps URL for `//# sourceMappingURL` but we'd also need to be sure that, when upgrading the js  libraries versions, we also update the source map URL (probably easy to automate that on CI)
