### ISSUE TITLE
ui not show 

### ISSUE THREAD

**Issue by awinlei** [arl/statsviz#97]
compile on windows and can not show UI

![image](https://user-images.githubusercontent.com/4607279/203508707-56ebbfff-e06d-42d3-8a37-0f1331165a91.png)

**Comment by arl** [comment]
Hi @awinlei and thank you for reporting!

Can you please the whole piece of Go code you're running so that we can try to reproduce it directly.
Thank you

**Comment by awinlei** [comment]
just compile on my windows PC，and then can not show the UI

**Comment by arl** [comment]
Without the code you're running it's very difficult to help you.

**Comment by arl** [comment]
Fixed by #106 and released in v0.5.2
